### ISSUE TITLE
Create step dialog fails due to issue with plugin

### ISSUE THREAD

**Issue by gmaxey** [electric-cloud/EF-ArtifactTemplate#1]
flow says:

class com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read proeprty 'g' of null

**Comment by urvashisingh** [comment]
@gmaxey The tab in the xml for the stepPicker property seems to be messing it up. When I removed the tabs (manually) from the properties, the step dialog comes up.
![image](https://cloud.githubusercontent.com/assets/10565877/17725949/4d79eb3e-6404-11e6-9769-9e474eda8849.png)

**Comment by gmaxey** [comment]
I can't find any way to get DSL generated properties to work. Once I open and save them in the UI, the error goes away.

``` groovy
deleteProperty '/server/ec_customEditors/pickerStep/EF-Satellite - Retrieve Package'

property "/server/ec_customEditors/pickerStep/EF-Satellite - Retrieve Package", value: """\
<step>
      <project>/plugins/EF-Satellite/project</project>
      <procedure>Retrieve Package</procedure>
      <category>System</category>
</step>\
""".stripIndent()
getProperty '/server/ec_customEditors/pickerStep/EF-Satellite - Retrieve Package'
```

**Comment by gmaxey** [comment]
Turns out that a description (blank will do) is required:

``` groovy
deleteProperty propertyName: "/server/ec_customEditors/pickerStep/test"
property "/server/ec_customEditors/pickerStep/test", description: "", value: """\
    <step>
       <project>/plugins/EC-FileOps/project</project>
       <procedure>AddTextToFile</procedure>
       <category>Utility</category>
    </step>
""".stripIndent()
```

Jira case: http://jira/browse/NMB-24135
